In [1]:
import secrets
import numpy as np
from sympy import Integer
# def generate_random_binary_iv(length):
#     iv = secrets.randbits(length)
#     return bin(iv)[2:].zfill(length)

# # Tạo khóa IV có chiều dài 128 bit
# IV = generate_random_binary_iv(128)

# # In ra khóa IV


# import random

# def generate_random_binary_string(length):
#     return ''.join(str(random.randint(0, 1)) for _ in range(length))

# # Tạo chuỗi nhị phân ngẫu nhiên có độ dài 278 bit
# K = generate_random_binary_string(278)

# # In ra chuỗi nhị phân K

IV= '01001010010011110110010101100101111011001010111011010101010001110101010000010000100001100010011000111001001010111100101011101001'
K= '10111000101001001111110100111010110110011101011110111001011100110110101111011011001111010011011100101101101110001110000100000010100001010100010100101001001000110110100000000111100011000000100111100010001000011011010011010011010000001000101100110111010010100010001110011000011100'
print("Khóa IV:", IV)
print("Chuỗi nhị phân K:", K)
def Xor(bin1, bin2):
    # Convert binary strings to integers
    int1 = int(bin1, 2)
    int2 = int(bin2, 2)
    
    # Perform XOR operation
    result = int1 ^ int2
    
    # Convert result back to binary string
    result_bin = bin(result)[2:].zfill(32)
    
    return result_bin


# Các giá trị ban đầu
IVP = IV[:32]
XP0 = K[:32]
IVS = IV[32:64]
XS0 = K[32:64]
IVL = IV[64:96]
XL0 = K[64:96]
IVT = IV[96:128]
XT0 = K[96:128]
Q0 = K[128:160]
Ps = K[160:192]
Pp = K[192:223]
Tr = K[223:233]
Kd = K[258:278]
# Thực hiện phép XOR cho mỗi biến
result_IVP_XP0 = Xor(IVP, XP0)
result_IVS_XS0 = Xor(IVS, XS0)
result_IVL_XL0 = Xor(IVL, XL0)
result_IVT_XT0 = Xor(IVT, XT0)

# In kết quả
print("IVP ^ XP0:", result_IVP_XP0)
print("IVS ^ XS0:", result_IVS_XS0)
print("IVL ^ XL0:", result_IVL_XL0)
print("IVT ^ XT0:", result_IVT_XT0)
# Các giá trị nhị phân của các phần tử e
e_binary = np.array([[0,K[233:238], K[238:243], K[243:248]],
                     [K[248:253],0, K[253:258], K[258:263]],
                     [K[263:268], K[268:273],0, K[273:278]],
                     [K[233:238], K[238:243], K[243:248],0 ]])

# Chuyển đổi các giá trị nhị phân sang thập phân
e_decimal = np.vectorize(lambda x: int(str(x), 2))(e_binary)

# Các giá trị của các phần tử e ở dạng thập phân
print("Giá trị của các phần tử e ở dạng thập phân:")
print(e_decimal)

# Giá trị mặc định của N
N = 32

# Tính toán các giá trị mới của M11, M22, M33, và M44
M11 = 2 ** N - np.sum(e_decimal, axis=1)[0]
M22 = 2 ** N - np.sum(e_decimal, axis=1)[1]
M33 = 2 ** N - np.sum(e_decimal, axis=1)[2]
M44 = 2 ** N - np.sum(e_decimal, axis=1)[3]

# Tạo ma trận M
new_values = np.array([[M11,0,0,0], 
              [0,M22,0,0], 
              [0,0,M33,0], 
              [0,0,0,M44]])
print("M",new_values)
print("M" ,M11)
def add_matrices(e_decimal, new_values):
    M = [[0]*4 for _ in range(4)]  # Tạo ma trận kết quả với tất cả các phần tử là 0

    # Thực hiện phép cộng từng phần tử của hai ma trận
    for i in range(4):
        for j in range(4):
            M[i][j] = e_decimal[i][j] + new_values[i][j]

    return M
# Thực hiện phép cộng
M = add_matrices(e_decimal, new_values)

# In ma trận kết quả
for row in M:
    print(row)

Khóa IV: 01001010010011110110010101100101111011001010111011010101010001110101010000010000100001100010011000111001001010111100101011101001
Chuỗi nhị phân K: 10111000101001001111110100111010110110011101011110111001011100110110101111011011001111010011011100101101101110001110000100000010100001010100010100101001001000110110100000000111100011000000100111100010001000011011010011010011010000001000101100110111010010100010001110011000011100
IVP ^ XP0: 11110010111010111001100001011111
IVS ^ XS0: 00110101011110010110110000110100
IVL ^ XL0: 00111111110010111011101100010001
IVT ^ XT0: 00010100100100110010101111101011
Giá trị của các phần tử e ở dạng thập phân:
[[ 0  2 25 23]
 [ 9  0  8 17]
 [25 16  0 28]
 [ 2 25 23  0]]
M [[4294967246          0          0          0]
 [         0 4294967262          0          0]
 [         0          0 4294967227          0]
 [         0          0          0 4294967246]]
M 4294967246
[4294967246, 2, 25, 23]
[9, 4294967262, 8, 17]
[25, 16, 4294967227, 28]
[2, 25, 

In [2]:
def calculate_XP(N, Pp_decimal, XP_prev):
    
    if not (1 <= Pp_decimal <= 2**(N-1) - 1) or not (1 <= XP_prev <= 2**N - 1):
        raise ValueError("Pp và XP_prev phải nằm trong khoảng cho phép.")
    
    # Tính toán giá trị XP(1) dựa trên công thức đã cho
    if XP_prev > 0 and XP_prev < Pp_decimal:
        XP_n = (2**N * XP_prev) // Pp_decimal
    elif XP_prev > Pp_decimal and XP_prev < 2**(N-1):
        XP_n = (2**N * (XP_prev - Pp_decimal)) // (2**(N-1) - Pp_decimal)
    elif XP_prev > 2**(N-1) and XP_prev < 2**N - Pp_decimal:
        XP_n = (2**N * (2**N - XP_prev - Pp_decimal)) // (2**(N-1) - Pp_decimal)
    elif XP_prev > 2**N - Pp_decimal and XP_prev < 2**N:
        XP_n = (2**N * (2**N - XP_prev)) // Pp_decimal
    else:
        XP_n = 2**N
    
    return XP_n

# Giả sử các giá trị đã cho
N = 32
# Pp_binary = '01111111111111111111111111111111'  # Pp ở dạng nhị phân 31 bit
Pp_binary = Pp
# XP_prev_binary = '00111111111111111111111111111111'  # XP(0) ở dạng nhị phân 32 bit
XP_prev_binary = result_IVP_XP0
# Chuyển đổi XP(0) từ dạng nhị phân sang thập phân
XP_prev = int(XP_prev_binary, 2) % 2**N
# Chuyển đổi Pp từ dạng nhị phân sang thập phân
Pp_decimal = int(Pp_binary, 2) % 2**(N-1)
# Tính toán giá trị XP(1)
XP_n = calculate_XP(N, Pp_decimal, XP_prev)

print(f"Giá trị XP(1) là: {XP_n}")


Giá trị XP(1) là: 496851341


In [3]:
def calculate_XL( N, XL_prev):
   
# XL_prev = XL_prev_mod_N % (2 ** N)
    if XL_prev != (3 * (2 ** (N - 2)) - 1) and XL_prev != (2 ** (N - 1)):
        XL_n = (XL_prev * (2 ** N - XL_prev)// 2**(N-2)) % (2 ** N)
    elif XL_prev == (3 * (2 ** (N - 2)) - 1):
        XL_n = (3 * (2 ** (N - 2))) * (2 ** (N - 1)) % (2 ** N)
    else:
        XL_n = (2 ** (N - 1)) * (2 ** (N - 1)) % (2 ** N)
    return XL_n

# Example usage:
N = 32  # Độ dài của dạng nhị phân
# XL_prev_mod_N ='10000010001001001000010111010001'
XL_prev_mod_N = result_IVL_XL0
# XL_prev_mod_N = int(input("Nhập giá trị XL(n-1) dạng nhị phân 32 bit mod 2**N: "), 2)
XL_prev = int(XL_prev_mod_N, 2) % (2 ** N)
XL_n = calculate_XL( N ,XL_prev)
 
print("Giá trị XL(1) dạng thập phân mod 2**N:", XL_n)
##



Giá trị XL(1) dạng thập phân mod 2**N: 3214363505


In [4]:
def calculate_XS(N, Ps_decimal, XS_prev):
   
   
   
    # Tính toán giá trị XS(1) dựa trên công thức đã cho
    if 0 < XS_prev < Ps_decimal:
        XS_n = (2**N * XS_prev) // Ps_decimal % (2 ** N)
    elif Ps_decimal < XS_prev < 2**N:
        XS_n = (2**N * (2**N - XS_prev)) // (2**N - Ps_decimal) % (2 ** N)
    else:
        XS_n = 2**N - 1 
        
    return int(XS_n)

# Thử nghiệm với giá trị ban đầu 
N = 32
# Ps_binary = "11011000101101101110010110110110"  # Giả sử giá trị nhị phân của Ps
# XS_prev_binary = "10101010101010101010101010101010"  # Giả sử giá trị nhị phân của XS(0)
Ps_binary = Ps
XS_prev_binary = result_IVS_XS0
 # Chuyển đổi XS(0) từ dạng nhị phân sang thập phân
XS_prev = int(XS_prev_binary, 2) % 2**N
    # Chuyển đổi Ps từ dạng nhị phân sang thập phân
Ps_decimal = int(Ps_binary, 2) % 2**N
# Tính toán giá trị XS(1)
XS_n = calculate_XS(N, Ps_decimal, XS_prev)

print(f"Giá trị XS(1) là: {XS_n}")


Giá trị XS(1) là: 2207743419


In [5]:
from sympy import Integer
def calculate_XT(N, XT_prev):
    # Chuyển XT_prev sang kiểu Integer để xử lý với số lớn
    XT_prev = Integer(XT_prev)
    # Tính toán giá trị XS(1) dựa trên công thức đã cho
    XT_n = (2 ** (-2*N + 2) * (4 * (XT_prev - 2**(N-1))**3 - 3 * 2**(2*N-2) * (XT_prev - 2**(N-1))) + 2**(N-1)) % 2**N
    return max(1, min(int(XT_n) % (2**N), 2**N - 1))  # Đảm bảo giá trị nằm trong khoảng từ 1 đến 2^N - 1

# Gán giá trị cho N và XT_prev_binary
N = 32
# result_IVT_XT0 = "10101010101010101010101010101010"  # Giả sử dữ liệu đầu vào là chuỗi nhị phân
XT_prev_binary = result_IVT_XT0
# Chuyển đổi XT(0) từ dạng nhị phân sang thập phân
XT_prev = int(XT_prev_binary, 2) % 2**N
    # Tính toán giá trị XT(1)
XT_n = calculate_XT(N, XT_prev)

print(f"Giá trị XT(1) là: {XT_n}")
################


# Chuyển đổi và in ra dạng nhị phân 32 bit
XT_n_2 = bin(XT_n)[2:].zfill(32)
print("Giá trị nhị phân 32 bit:", XT_n_2)


Giá trị XT(1) là: 2476545581
Giá trị nhị phân 32 bit: 10010011100111010001011000101101


In [6]:
class LFSR:
    
    def __init__(self, seed, polynomial):
        self.state = seed
        self.polynomial = polynomial

    def shift(self):
        #Tính toán giá trị
        feedback = (self.state >> 32) ^ ((self.state >> 22) & 1) ^ ((self.state >> 3) & 1) ^ ((self.state >> 2) & 1)
        # Dịch chuyển trạng thái
        self.state = (self.state >> 1) | (feedback << 31)

        
    def get_output(self):
        return self.state
seed_binary = Q0
seed_decimal = int(seed_binary, 2)
# Xác định đa thức nguyên thủy
primitive_polynomial = [32, 22, 2, 1, 0]

# Khởi tạo LFSR với giá trị khởi đầu và đa thức
lfsr = LFSR(seed=seed_decimal, polynomial=primitive_polynomial)

# Tạo ra 10 đầu ra
for _ in range(13):
    print(bin(lfsr.get_output())[2:].zfill(32))
    lfsr.shift()
###################


10000101010001010010100100100011
11000010101000101001010010010001
01100001010100010100101001001000
00110000101010001010010100100100
10011000010101000101001010010010
11001100001010100010100101001001
11100110000101010001010010100100
11110011000010101000101001010010
01111001100001010100010100101001
10111100110000101010001010010100
01011110011000010101000101001010
00101111001100001010100010100101
10010111100110000101010001010010


In [7]:
# Khởi tạo LFSR với giá trị seed và đa thức
lfsr = LFSR(seed=seed_decimal, polynomial=primitive_polynomial)

# Lặp 14 lần để dịch chuyển LFSR
for _ in range(54):
    lfsr.shift()

# Lấy giá trị của LFSR tại thời điểm hiện tại (lần thứ 14)
LFSR_n = lfsr.get_output()

# In ra giá trị hiện tại của LFSR
print (LFSR_n)
print(bin(LFSR_n)[2:].zfill(32))
#Tính XTI_1 

    # Chuyển đổi XT(0) từ dạng nhị phân sang thập phân
XTI_n_2 = Xor(XT_n_2,bin(LFSR_n)[2:].zfill(32))
XTI_n = int(XTI_n_2, 2) % 2**N
  


# In ra giá trị XTI_n dạng thập phân
print("XTI_n:", XTI_n)

2372917383
10001101011011111101100010000111
XTI_n: 519229098


In [8]:
import numpy as np
# Tạo ma trận 4x1 và đưa giá trị XP_n vào
matrix_4x1 = np.zeros((4, 1))
matrix_4x1[0, 0] = XP_n
matrix_4x1[1, 0] = XS_n
matrix_4x1[2, 0] = XL_n
matrix_4x1[3, 0] = XTI_n
print("Ma trận 4x1:")
print(matrix_4x1)

Ma trận 4x1:
[[4.96851341e+08]
 [2.20774342e+09]
 [3.21436350e+09]
 [5.19229098e+08]]


In [9]:
print(M)

[[4294967246, 2, 25, 23], [9, 4294967262, 8, 17], [25, 16, 4294967227, 28], [2, 25, 23, 4294967246]]


In [10]:
import numpy as np


# Ma trận 4x1
matrix_4x1 = np.array([[
    XP_n], [XS_n], [XL_n], [XTI_n]])

# Ma trận M

# Nhân hai ma trận
M_A = (M @ matrix_4x1) % (2**32)

print("Kết quả sau khi nhân ma trận:")
print(M_A)


Kết quả sau khi nhân ma trận:
[[3154799931]
 [2604894193]
 [3701268376]
 [1076978768]]


In [11]:
import numpy as np

# Giả sử result_matrix đã được tính trước đó

# Lấy kết quả của từng hàng
row1_result = M_A[0, 0]
row2_result = M_A[1, 0]
row3_result = M_A[2, 0]
row4_result = M_A[3, 0]

# Lấy phần dư mod 2^32
XPC_1 = M_A[0, 0] % (2**32)
XSC_1 = M_A[1, 0] % (2**32)
XLC_1 = M_A[2, 0] % (2**32)
XTIC_1 = M_A[3, 0] % (2**32)

print("Kết quả của từng hàng sau khi lấy phần dư mod 2^32:")
print("Row 1:", XPC_1)
print("Row 2:", XSC_1)
print("Row 3:", XLC_1)
print("Row 4:", XTIC_1)


Kết quả của từng hàng sau khi lấy phần dư mod 2^32:
Row 1: 3154799931
Row 2: 2604894193
Row 3: 3701268376
Row 4: 1076978768


In [12]:
# Xn1 tính toán
Xn = XPC_1 ^ XSC_1 ^ XLC_1 ^ XTIC_1 
print(Xn)
#### S-box
# S_box = [[0 for _ in range(16)] for _ in range(16)]

# # Tạo một set để lưu trữ các giá trị đã xuất hiện
# S_values = set()

# # Tính toán giá trị V ban đầu và đẩy vào S box
# V_n = Xn % 256
# S_box[0][0] = V_n
# S_values.add(V_n)
# t = 1

3152302338


In [13]:


# Lưu trữ giá trị ban đầu
XP_prev = XPC_1
XS_prev = XSC_1
XL_prev = XLC_1
XT_prev = XTIC_1
LFSR_prev = LFSR_n
Xn_values = []

# Tính toán các giá trị XP(n), XL(n), XS(n), XT(n) với n trong khoảng 2 < n < 100
for n in range(2, 1600):
    Xn_values.append(Xn)
    # Tính toán giá trị XP, XL, XS, XT cho vòng lặp hiện tại
    XP_n = calculate_XP(N, Pp_decimal, XP_prev)
    XL_n = calculate_XL(N, XL_prev)
    XS_n = calculate_XS(N, Ps_decimal, XS_prev)
    XT_n = calculate_XT(N, XT_prev)
    
    # Cập nhật giá trị LFSR
    lfsr.shift()
    LFSR_n = lfsr.get_output()
    
    # Tính giá trị XT_n
    XTI_n = (XT_n ^ LFSR_n) % 2**N
    
    
    # In ra giá trị của XP(n), XL(n), XS(n), XT(n)
    # print(f"Giá trị XP({n}) là: {XP_n}")
    # print(f"Giá trị XL({n}) là: {XL_n}")
    # print(f"Giá trị XS({n}) là: {XS_n}")
    # print(f"Giá trị XT({n}) là: {XT_n}")

    # Tính toán Xn và in ra giá trị cuối cùng
    matrix_4x1 = np.zeros((4, 1))
    matrix_4x1[0, 0] = XP_n
    matrix_4x1[1, 0] = XS_n
    matrix_4x1[2, 0] = XL_n
    matrix_4x1[3, 0] = XTI_n

    matrix_4x1 = np.array([[XP_n], [XS_n], [XL_n], [XTI_n]])
    # Ma trận M
    # Nhân hai ma trận
    M_A = (M @ matrix_4x1) % (2**32)

    XPC_n = M_A[0, 0] % (2**32)
    XSC_n = M_A[1, 0] % (2**32)
    XLC_n = M_A[2, 0] % (2**32)
    XTIC_n = M_A[3, 0] % (2**32)
    
    # Cập nhật giá trị cho vòng lặp tiếp theo
    XP_prev = XPC_n
    XS_prev = XSC_n
    XL_prev = XLC_n
    XT_prev = XTIC_n
    LFSR_prev = LFSR_n
    # Tính toán Xn và in ra giá trị cuối cùng
    Xn = XPC_n ^ XSC_n ^ XLC_n ^ XTIC_n 
    # print(f"Giá trị Xn({n}) là: {Xn}")
    ####################
  

In [14]:
# Khởi tạo một set để lưu trữ các giá trị đã xuất hiện
S_values = set()

# Khởi tạo S_box 16x16 với tất cả các giá trị ban đầu là 0
S_box = [[0 for _ in range(16)] for _ in range(16)]

# Biến đếm số lượng giá trị duy nhất đã được thêm vào S_box
t = 0

# Tính toán V = Xn mod 256 cho mỗi giá trị Xn và đẩy vào S_box
for Xn in Xn_values:
    V = Xn % 256
    # Nếu giá trị V chưa xuất hiện, thêm vào S_box và vào set unique_values
    if V not in S_values:
        # Tìm vị trí cho giá trị V trong S_box
        row = t // 16
        col = t % 16
        # Lưu giá trị V vào S_box tại vị trí tương ứng
        S_box[row][col] = V
        # Thêm giá trị V vào set unique_values
        S_values.add(V)
        # Tăng biến đếm lên 1
        t += 1
    # Nếu S_box đã đầy 256 giá trị, dừng vòng lặp
    if t > 255:
        break

# In ra S_box
print("S_box 16x16:")
for row in S_box:
    print(row)


S_box 16x16:
[2, 193, 0, 32, 162, 160, 134, 165, 41, 16, 228, 252, 169, 254, 38, 113]
[182, 213, 44, 237, 92, 119, 184, 240, 216, 147, 4, 233, 129, 192, 244, 197]
[176, 109, 122, 39, 224, 247, 49, 30, 51, 98, 102, 110, 211, 231, 20, 12]
[7, 205, 27, 179, 57, 73, 56, 151, 126, 105, 141, 104, 242, 203, 171, 236]
[8, 223, 209, 65, 25, 83, 74, 234, 106, 186, 204, 207, 153, 11, 81, 45]
[71, 180, 154, 232, 101, 97, 133, 225, 181, 99, 103, 17, 125, 120, 155, 86]
[59, 227, 31, 9, 175, 189, 158, 15, 24, 200, 95, 94, 1, 90, 123, 245]
[19, 76, 167, 144, 127, 210, 132, 22, 202, 69, 77, 156, 251, 201, 79, 115]
[87, 61, 82, 212, 37, 195, 198, 62, 85, 128, 214, 93, 29, 117, 107, 239]
[42, 116, 206, 222, 137, 183, 88, 148, 46, 150, 5, 174, 67, 188, 136, 84]
[89, 241, 18, 3, 108, 191, 143, 112, 138, 52, 163, 63, 118, 78, 235, 172]
[53, 173, 190, 159, 91, 140, 246, 168, 238, 217, 166, 187, 13, 170, 142, 199]
[68, 28, 75, 100, 10, 243, 145, 54, 23, 194, 215, 220, 111, 80, 219, 161]
[250, 114, 149, 14, 34

In [15]:
print (S_box)

[[2, 193, 0, 32, 162, 160, 134, 165, 41, 16, 228, 252, 169, 254, 38, 113], [182, 213, 44, 237, 92, 119, 184, 240, 216, 147, 4, 233, 129, 192, 244, 197], [176, 109, 122, 39, 224, 247, 49, 30, 51, 98, 102, 110, 211, 231, 20, 12], [7, 205, 27, 179, 57, 73, 56, 151, 126, 105, 141, 104, 242, 203, 171, 236], [8, 223, 209, 65, 25, 83, 74, 234, 106, 186, 204, 207, 153, 11, 81, 45], [71, 180, 154, 232, 101, 97, 133, 225, 181, 99, 103, 17, 125, 120, 155, 86], [59, 227, 31, 9, 175, 189, 158, 15, 24, 200, 95, 94, 1, 90, 123, 245], [19, 76, 167, 144, 127, 210, 132, 22, 202, 69, 77, 156, 251, 201, 79, 115], [87, 61, 82, 212, 37, 195, 198, 62, 85, 128, 214, 93, 29, 117, 107, 239], [42, 116, 206, 222, 137, 183, 88, 148, 46, 150, 5, 174, 67, 188, 136, 84], [89, 241, 18, 3, 108, 191, 143, 112, 138, 52, 163, 63, 118, 78, 235, 172], [53, 173, 190, 159, 91, 140, 246, 168, 238, 217, 166, 187, 13, 170, 142, 199], [68, 28, 75, 100, 10, 243, 145, 54, 23, 194, 215, 220, 111, 80, 219, 161], [250, 114, 149, 14, 3

In [21]:

# Chuyển ma trận thành danh sách một chiều
custom_Sbox = [item for sublist in S_box for item in sublist]

print(custom_Sbox )
AES_Sbox = [
    0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
    0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
    0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
    0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
    0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
    0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
    0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
    0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
    0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
    0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
    0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
    0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
    0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
    0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
    0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
    0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16
]
custom_Sbox_hex = [hex(num) for num in custom_Sbox]
custom_Sbox_hex_16x16 = [custom_Sbox_hex[i:i+16] for i in range(0, len(custom_Sbox_hex), 16)]

# In ra ma trận 16x16

custom_Sbox_aes = [AES_Sbox[num] for num in custom_Sbox]
print(custom_Sbox_aes)
custom_Sbox_aes_16x16 = [custom_Sbox_aes[i:i+16] for i in range(0, len(custom_Sbox_aes), 16)]

# In ra ma trận 16x16
for row in custom_Sbox_aes_16x16:
    print(' '.join(['{:02X}'.format(num) for num in row]))
custom_Sbox_aes_hex = [hex(num) for num in custom_Sbox_aes]
print(custom_Sbox_aes_hex)

[2, 193, 0, 32, 162, 160, 134, 165, 41, 16, 228, 252, 169, 254, 38, 113, 182, 213, 44, 237, 92, 119, 184, 240, 216, 147, 4, 233, 129, 192, 244, 197, 176, 109, 122, 39, 224, 247, 49, 30, 51, 98, 102, 110, 211, 231, 20, 12, 7, 205, 27, 179, 57, 73, 56, 151, 126, 105, 141, 104, 242, 203, 171, 236, 8, 223, 209, 65, 25, 83, 74, 234, 106, 186, 204, 207, 153, 11, 81, 45, 71, 180, 154, 232, 101, 97, 133, 225, 181, 99, 103, 17, 125, 120, 155, 86, 59, 227, 31, 9, 175, 189, 158, 15, 24, 200, 95, 94, 1, 90, 123, 245, 19, 76, 167, 144, 127, 210, 132, 22, 202, 69, 77, 156, 251, 201, 79, 115, 87, 61, 82, 212, 37, 195, 198, 62, 85, 128, 214, 93, 29, 117, 107, 239, 42, 116, 206, 222, 137, 183, 88, 148, 46, 150, 5, 174, 67, 188, 136, 84, 89, 241, 18, 3, 108, 191, 143, 112, 138, 52, 163, 63, 118, 78, 235, 172, 53, 173, 190, 159, 91, 140, 246, 168, 238, 217, 166, 187, 13, 170, 142, 199, 68, 28, 75, 100, 10, 243, 145, 54, 23, 194, 215, 220, 111, 80, 219, 161, 250, 114, 149, 14, 34, 33, 66, 26, 185, 72, 48,

In [17]:
# import random

# # Khởi tạo hộp S-box
# S_box = [[0]*16 for _ in range(16)]

# # Danh sách để theo dõi các giá trị V đã xuất hiện
# S_value= []

# # Khởi tạo giá trị ban đầu của X và t
# Xn = XPC_1
# t = 0

# # Tính toán giá trị cho hộp S-box
# for i in range(16):
#     for j in range(16):
#         # Tính giá trị V và kiểm tra xem đã sử dụng chưa
#         V = Xn % 256
#         while V in S_values:
#             Xn = (a*Xn + b) % (2**32)  # Tính toán Xn mới nếu giá trị V đã được sử dụng
#             V = Xn % 256
#         # Thêm giá trị V vào danh sách đã sử dụng
#         S_values.append(V)
#         # Cập nhật giá trị S[t] trong hộp S-box
#         S_box[i][j] = V
#         # Tăng giá trị t lên 1
#         t += 1
#         # Nếu t vượt quá 255, dừng quá trình tính toán
#         if t > 255:
#             break
#     if t > 255:
#         break

# # In ra hộp S-box
# for row in S_box:
#     print(row)


In [18]:
# custom_Sbox = [
#     2, 193, 0, 32, 162, 160, 134, 165, 41, 16, 228, 252, 169, 254, 38, 113,
#     182, 213, 44, 237, 92, 119, 184, 240, 216, 147, 4, 233, 129, 192, 244, 197,
#     176, 109, 122, 39, 224, 247, 49, 30, 51, 98, 102, 110, 211, 231, 20, 12,
#     7, 205, 27, 179, 57, 73, 56, 151, 126, 105, 141, 104, 242, 203, 171, 236,
#     8, 223, 209, 65, 25, 83, 74, 234, 106, 186, 204, 207, 153, 11, 81, 45,
#     71, 180, 154, 232, 101, 97, 133, 225, 181, 99, 103, 17, 125, 120, 155, 86,
#     59, 227, 31, 9, 175, 189, 158, 15, 24, 200, 95, 94, 1, 90, 123, 245,
#     19, 76, 167, 144, 127, 210, 132, 22, 202, 69, 77, 156, 251, 201, 79, 115,
#     87, 61, 82, 212, 37, 195, 198, 62, 85, 128, 214, 93, 29, 117, 107, 239,
#     42, 116, 206, 222, 137, 183, 88, 148, 46, 150, 5, 174, 67, 188, 136, 84,
#     89, 241, 18, 3, 108, 191, 143, 112, 138, 52, 163, 63, 118, 78, 235, 172,
#     53, 173, 190, 159, 91, 140, 246, 168, 238, 217, 166, 187, 13, 170, 142, 199,
#     68, 28, 75, 100, 10, 243, 145, 54, 23, 194, 215, 220, 111, 80, 219, 161,
#     250, 114, 149, 14, 34, 33, 66, 26, 185, 72, 48, 196, 130, 152, 248, 255,
#     146, 96, 178, 21, 50, 221, 139, 218, 60, 121, 230, 229, 253, 208, 131, 36,
#     64, 226, 47, 55, 157, 177, 249, 43, 124, 164, 35, 40, 70, 135, 58, 6
# ]

# AES_Sbox = [
#     0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
#     0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
#     0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
#     0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
#     0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
#     0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
#     0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
#     0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
#     0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
#     0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
#     0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
#     0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
#     0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
#     0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
#     0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
#     0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16
# ]

# # # # # Tạo một từ điển ánh xạ từng giá trị trong custom_Sbox với giá trị tương ứng từ AES_Sbox
# # # custom_Sbox_mapping = {AES_Sbox[i]: custom_Sbox[i] for i in range(256)}

# # # # Thay thế mỗi giá trị trong custom_Sbox bằng giá trị từ AES_Sbox
# # # custom_Sbox_replacement = [custom_Sbox_mapping[value] for value in range(256)]

# # # print(custom_Sbox_replacement)
# # # custom_Sbox_replacement_hex = [hex(value) for value in custom_Sbox_replacement]
# custom_Sbox_hex = [hex(num) for num in custom_Sbox]
# custom_Sbox_hex_16x16 = [custom_Sbox_hex[i:i+16] for i in range(0, len(custom_Sbox_hex), 16)]

# # In ra ma trận 16x16
# for row in custom_Sbox_hex_16x16:
#     print(' '.join(row))


# # Sbox_hex = [hex(value) for value in custom_Sbox]  
# # print(Sbox_hex)
# # # Loại bỏ tiền tố "0x" và chuyển đổi thành số nguyên
# # S_box_int = [int(x, 16) for x in Sbox_hex]

# # # Tạo danh sách AES_Sbox từ S_box_int
# # AES_Sbox = [0] * 256
# # for i, value in enumerate(S_box_int):
# #     AES_Sbox[i] = value

# # # # Lấy giá trị từ vị trí [0, 1] và [5, 5]
# # # value_0_1 = AES_Sbox[0 * 16 + 1]
# # # value_5_5 = AES_Sbox[5 * 16 + 5]

# # print("Giá trị tại vị trí [0, 1]:", hex(value_0_1))
# # print("Giá trị tại vị trí [5, 5]:", hex(value_5_5))
# custom_Sbox_aes = [AES_Sbox[num] for num in custom_Sbox]
# print(custom_Sbox_aes)
# custom_Sbox_aes_16x16 = [custom_Sbox_aes[i:i+16] for i in range(0, len(custom_Sbox_aes), 16)]

# # In ra ma trận 16x16
# for row in custom_Sbox_aes_16x16:
#     print(' '.join(['{:02X}'.format(num) for num in row]))
# custom_Sbox_aes_hex = [hex(num) for num in custom_Sbox_aes]
# print(custom_Sbox_aes_hex)

In [19]:
# ud = Kd[:5]
# vd = Kd[5:10]
# rid = Kd[10:15]
# rjd = Kd[15:20]
# print (ud , vd, rid , rjd)

In [20]:
M = 32
print(s_box_matrix)

# Định nghĩa hàm Modified 2-D Cat Map
def modified_2d_cat_map(i, j, ud, vd, rid, rjd, M):
    Z1 = (rid + rjd) % M
    Z2 = (ud * vd + 1) % M
    Z3 = (vd * i + rjd) % M
    in_ = (i + ud * j + Z1) % M
    jn = (Z3 + Z2 * j) % M 
    return in_, jn

# Khóa động

ud = int(Kd[:5], 2)
vd = int(Kd[5:10], 2)
rid = int(Kd[10:15], 2)
rjd = int(Kd[15:20], 2)
print (ud,vd,rid,rjd)
# Số hàng và số cột của ma trận
M = 32

# Ma trận hoán vị
s_box_permuted = [['' for _ in range(M)] for _ in range(M)]


# Phép hoán vị sử dụng Modified 2-D Cat Map
for i in range(M):
    for j in range(M):
        in_, jn = modified_2d_cat_map(i, j, ud, vd, rid, rjd, M)
        print("in_:", in_, "jn:", jn)  # In ra giá trị của in_ và jn để kiểm tra
        if in_ < M and jn < M:  # Kiểm tra xem chỉ số hàng và cột có nằm trong phạm vi hợp lệ không
            s_box_permuted[in_][jn] = s_box_matrix[i][j]
        else:
            print("Invalid indices:", in_, jn)

# In ma trận hoán vị
for row in s_box_permuted:
    print(' '.join(row))




NameError: name 's_box_matrix' is not defined